In [1]:
import numpy as np
import plotly.graph_objects as go

# Number of points per circle
n_samples = 500
noise_std = 0.05  # Standard deviation of Gaussian noise

# Generate the first circle in the XY-plane (centered at (0,0,0))
theta1 = np.linspace(0, 2 * np.pi, n_samples)
x1 = np.cos(theta1)
y1 = np.sin(theta1)
z1 = np.zeros_like(theta1)  # Circle in the XY-plane

# Generate the second circle in the YZ-plane (centered at (0,1,0))
theta2 = np.linspace(0, 2 * np.pi, n_samples)
x2 = np.zeros_like(theta2)  # Center at (0,1,0), ensuring interlock
y2 = np.ones_like(theta2) + np.cos(theta2)  # Shift center to (0,1,0)
z2 = np.sin(theta2)

# Stack the data
X = np.vstack([
    np.column_stack([x1, y1, z1]),  # First circle
    np.column_stack([x2, y2, z2])   # Second circle (interlocking)
])

# Add 3D Gaussian noise
X_noisy = X + np.random.normal(scale=noise_std, size=X.shape)

# Labels for classification
y_labels = np.hstack([np.zeros(n_samples), np.ones(n_samples)])

# Create Plotly 3D scatter plot
fig = go.Figure()

# Add first circle (XY-plane)
fig.add_trace(go.Scatter3d(
    x=X_noisy[:n_samples, 0], 
    y=X_noisy[:n_samples, 1], 
    z=X_noisy[:n_samples, 2],
    mode='markers',
    marker=dict(size=3, color='blue', opacity=0.7),
    name="Circle 1"
))

# Add second circle (YZ-plane)
fig.add_trace(go.Scatter3d(
    x=X_noisy[n_samples:, 0], 
    y=X_noisy[n_samples:, 1], 
    z=X_noisy[n_samples:, 2],
    mode='markers',
    marker=dict(size=3, color='red', opacity=0.7),
    name="Circle 2"
))

# Set layout options
fig.update_layout(
    title="Interlocking Circles in 3D",
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z"
    ),
    margin=dict(l=0, r=0, b=0, t=40)  # Adjust margins for better view
)

# Show interactive plot
fig.show()


In [2]:
import numpy as np

def make_interlocking_circles_3d(n_samples=1000, noise=0.05, random_state=None):
    """
    Generates a 3D dataset of two interlocking circles.
    
    Parameters:
    - n_samples (int): Total number of points (split evenly between the two circles).
    - noise (float): Standard deviation of Gaussian noise.
    - random_state (int, optional): Random seed for reproducibility.
    
    Returns:
    - X (ndarray): (n_samples, 3) array of 3D points.
    - y (ndarray): (n_samples,) array of labels (0 or 1).
    """
    if random_state is not None:
        np.random.seed(random_state)

    # Ensure even split of samples between the two circles
    n_samples_per_circle = n_samples // 2

    # Generate the first circle in the XY-plane (centered at (0,0,0))
    theta1 = np.linspace(0, 2 * np.pi, n_samples_per_circle)
    x1 = np.cos(theta1)
    y1 = np.sin(theta1)
    z1 = np.zeros_like(theta1)

    # Generate the second circle in the YZ-plane (centered at (0,1,0)), interlocking with the first
    theta2 = np.linspace(0, 2 * np.pi, n_samples_per_circle)
    x2 = np.zeros_like(theta2)
    y2 = np.ones_like(theta2) + np.cos(theta2)  # Shifted up by 1
    z2 = np.sin(theta2)

    # Stack the data
    X = np.vstack([
        np.column_stack([x1, y1, z1]),  # First circle
        np.column_stack([x2, y2, z2])   # Second circle (interlocking)
    ])

    # Labels: 0 for first circle, 1 for second circle
    y = np.hstack([np.zeros(n_samples_per_circle), np.ones(n_samples_per_circle)])

    # Add Gaussian noise
    X += np.random.normal(scale=noise, size=X.shape)

    return X, y

# Example usage
X, y = make_interlocking_circles_3d(n_samples=1000, noise=0.05, random_state=42)

# Print first 5 points
print("First 5 points:\n", X[:5])
print("First 5 labels:\n", y[:5])


First 5 points:
 [[ 1.02483571e+00 -6.91321506e-03  3.23844269e-02]
 [ 1.07607222e+00  8.83552262e-04 -1.17068478e-02]
 [ 1.07864356e+00  6.35521822e-02 -2.34737193e-02]
 [ 1.02641462e+00  1.45947936e-02 -2.32864877e-02]
 [ 1.01083000e+00 -4.53190891e-02 -8.62458916e-02]]
First 5 labels:
 [0. 0. 0. 0. 0.]


In [7]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000, noise=0.05, random_state=42)
print(np.shape(X))
print(np.shape(y))

(1000, 2)
(1000,)


In [25]:
# Generate dataset
X, y = make_interlocking_circles_3d(n_samples=1000, noise=0.25, random_state=42)

print(np.shape(X))
print(np.shape(y))

(1000, 3)
(1000,)


In [26]:




# Create interactive 3D scatter plot
fig = go.Figure()

# Plot first circle (label = 0)
fig.add_trace(go.Scatter3d(
    x=X[y == 0, 0], 
    y=X[y == 0, 1], 
    z=X[y == 0, 2],
    mode='markers',
    marker=dict(size=3, color='blue', opacity=0.7),
    name="Circle 1"
))

# Plot second circle (label = 1)
fig.add_trace(go.Scatter3d(
    x=X[y == 1, 0], 
    y=X[y == 1, 1], 
    z=X[y == 1, 2],
    mode='markers',
    marker=dict(size=3, color='red', opacity=0.7),
    name="Circle 2"
))

fig.update_layout(
    title="Interlocking Circles in 3D",
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z"
    ),
    margin=dict(l=0, r=0, b=0, t=40)
)

fig.show()